version: "2"

services:
  flask:
    build: flask
    image: tburge/dice-data-collector:latest
    command: "bash ./wrapper.sh"
    restart: always
    ports:
      - "80:5000"
      - "5555:5555"
    networks:
      - dice-ddc

  redis:
    image: 'redis'
    command: "redis-server"
    restart: always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - dice-ddc

volumes:
    redis:

networks:
    dice-ddc:
